HWID: ''
kit-map: true
announcements:
  list: []
  delay: 300
broadcast:
  format: '&e[Base] %1$s'
chat:
  enabled: true
  slowed: false
  slowed-delay: 15
server:
  teamspeak: 'ts.phonexmc.us'
  store: 'store.phonexmc.us'
full-server-kick-message: '&cThe server is full. &e(%1$s/%2$s) \n\n&cDonate to get a premium slot. {donate link}'
lobby-in-bungee: 'hub1'
command-kits: 'gkits'
servers-inventory:
 slot-1:
   activated: true
   server: 'squads'
 slot-2:
   activated: true
   server: 'kitmap'
 slot-3:
   activated: false
   server: 'server'
 slot-4:
   activated: false
   server: 'server'
 slot-5:
   activated: false
   server: 'server'
 slot-6:
   activated: false
   server: 'server'
 slot-7:
   activated: false
   server: 'server'
 slot-8:
   activated: false
   server: 'server'
 slot-9:
   activated: false
   server: 'server'
messages:
   upload-video: #Variable %player%, %link%
     - '&7&m-------------------------------------'
     - '&6%player% &euploaded a new video!'
     - '&6Video Link: &7%link%'
     - '&7&m-------------------------------------'
   record: #Variable %player%, %channel%
     - '&7&m-------------------------------------'
     - '&5%player% &fis now recording!'
     - '&fChannel&7: &d%channel%'
     - '&7&m-------------------------------------'
   twitch: #Variable %player%, %channel%
     - '&7&m-------------------------------------'
     - '&5&l%player% &dStarted a stream!'
     - '&dChannel&7: &f%channel%'
     - '&7&m-------------------------------------'
   media-command: #Variable %player%
     - '&7&m------------------------------'
     - '&c&lYouTuber &fRequirments'
     - ' &7» &f400 Subscribers'
     - ' &7» &f1 Video on Server'
     - ''
     - '&d&l&oFamous &fRequirments'
     - ' &7» &f800 Subscribers'
     - ' &7» &f1 Video of Server'
     - ' &7» &f200 Views'
     - ''
     - '&d&l&o&nPartner &fRequirments'
     - ' &7» &f3k Subscribers'
     - ' &7» &f3 Video of Server'
     - ' &7» &f800 Views per Video'
     - '&7&m------------------------------'
   list-command:
     - '&7&m------------------------------'
     - '&6 » &eThere are &6&l%online% &eplayers connected to the &6&lServer'
     - '&7&m------------------------------'
freeze-teamspeak: 'ts.phonexmc.us'
freeze-message-interval: 3
freeze-disabled-commands:
  - 'msg'